# https://travis-ci.org/pytorch/pytorch
language: python
python:
    - 2.7.8
    - 2.7
    - 3.5
    - nightly

install:
    - export CC="gcc-4.8"
    - export CXX="g++-4.8"
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install .

script:
    - ./test/run_test.sh

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

# This reportedly works around an issue downloading packages from pypi on
# travis.  Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
    fast_finish: true
    include:
        env: LINT_CHECK
        python: "2.7"
        addons: true
        install: pip install pep8
        script: pep8 setup.py
